# Generated by Django 4.0.2 on 2022-02-23 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_info_save_to_excel', '0003_remove_cv_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CV',
        ),
    ]
