# Generated by Django 4.0.2 on 2022-02-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50, verbose_name='Ad')),
                ('lastName', models.CharField(max_length=50, verbose_name='Soyad')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('validityTime', models.IntegerField(verbose_name='Geçerlilik Süresi')),
            ],
        ),
    ]
