# Generated by Django 4.0.2 on 2022-02-12 13:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ContactInfoSaveToExcel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='uniqueId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
