# Generated by Django 4.0.2 on 2022-02-13 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContactInfoSaveToExcel', '0002_contactinfo_uniqueid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='uniqueId',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='validityTime',
        ),
    ]
