# Generated by Django 4.0.2 on 2022-02-19 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContactInfoSaveToExcel', '0002_cv_delete_deneme_delete_deneme2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='title',
        ),
    ]
