# Generated by Django 4.0.2 on 2022-02-13 11:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ContactInfoSaveToExcel', '0003_remove_contactinfo_uniqueid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='uniqueId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='validityTime',
            field=models.IntegerField(null=True, verbose_name='Geçerlilik Süresi'),
        ),
    ]
